# Generated by Django 2.1.7 on 2020-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='TiTLE')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
